Fixing a few open things
staxfur/authfox pull request #66
Opened 2022-06-09 21:08 UTC by MCWertGaming

This PR solves a few issues that are dangling around:
- #55: Fixed http code 200 being returned on wrong data
- #17: Fixed a bug in the session rotation that leads to overwriting the last session instead of the first
- #44: The session TTL is now increased when it's used so the session keeps being valid
- #65: Added missing error handling for some functions
- #19: Updated the swagger reference with the removed delete endpoint and the new http status code 406 for invalid headers
- #39: Added repo files like issue templates

2022-06-09 21:37 UTC, Sigmanificient requested changes

2022-06-09 21:37 UTC, Sigmanificient commented on README.md
>  ```
Why this is not handled within a `.env` file?

2022-06-09 21:37 UTC, Sigmanificient commented on internal/helper/session.go
> +			return sessionPair{Token: token, UserID: *userID + "5", VerifyOnly: verify}, nil
This contains a lot of code repetition, there is surely a better to handle the session

2022-06-09 21:41 UTC, FissionFeline approved these changes, later dismissed

2022-06-09 22:21 UTC, staxfur commented on README.md
>  ```
because authfox will run in a docker container in production, allowing users to use a .env file for development would mean extra code that is not necessary. So I guess that a better approach would be automating the configuration of the development environment set up, like visual studio code container work spaces (which would also handle the DB setup so people not even have to run the docker compose file for quickly getting started). It's tracked in #45.

2022-06-09 22:22 UTC, MCWertGaming commented on internal/helper/session.go
> +			return sessionPair{Token: token, UserID: *userID + "5", VerifyOnly: verify}, nil
I have added a TODO there because the the session system needs refactoring (at least the permissive session). I'll quickly do that.

2022-06-09 22:49 UTC, MCWertGaming commented on internal/helper/session.go
> +			return sessionPair{Token: token, UserID: *userID + "5", VerifyOnly: verify}, nil
Refactored in 86ce57a9da5bdc613970675d7b4d8838542c0ef4. Does it look fine now?

2022-06-10 17:10 UTC, Sigmanificient approved these changes

2022-06-11 18:12 UTC, Alekuso approved these changes

2022-06-11 18:16 UTC, merged